version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always

    ports:
      # HTTP
      - 9295:9295
    environment:
      NIFI_WEB_HTTP_PORT: 9295

    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
